model_name_or_path: Qwen/Qwen1.5-0.5B

stage: sft
do_train: true
finetuning_type: lora
lora_target: all

dataset: CIKM_qc_demo
template: default
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

output_dir: saves/Qwen1.5-0.5B/lora/sft
logging_steps: 10
save_steps: 5
plot_loss: true
overwrite_output_dir: true

per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: false
ddp_timeout: 180000000

val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500